=== serverlessworkflow/specification/sdk/java/api/src/main/resources/schema/workflow.json
{
  "$id": "https://wg-serverless.org/workflow.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Serverless Workflow is a vendor-neutral specification for defining the model of workflows responsible for orchestrating event-driven serverless applications.",
  "type": "object",
  "extendsJavaClass": "io.cncf.serverlessworkflow.api.workflow.BaseWorkflow",
  "javaType": "io.cncf.serverlessworkflow.api.Workflow",
  "javaInterfaces": [
    "java.io.Serializable"
  ],
  "properties": {
    "id": {
      "type": "string",
      "description": "Workflow unique identifier",
      "minLength": 1
    },
    "name": {
      "type": "string",
      "description": "Workflow name",
      "minLength": 1
    },
    "description": {
      "type": "string",
      "description": "Workflow description"
    },
    "version": {
      "type": "string",
      "description": "Workflow version"
    },
    "schemaVersion": {
      "type": "string",
      "description": "Serverless Workflow schema version"
    },
    "dataInputSchema": {
      "type": "string",
      "description": "URI to JSON Schema that workflow data input adheres to"
    },
    "dataOutputSchema": {
      "type": "string",
      "description": "URI to JSON Schema that workflow data output adheres to"
    },
    "metadata": {
      "$ref": "metadata/metadata.json"
    },
    "expressionLanguage": {
      "type": "string",
      "description": "Default expression language to be used throughout the workflow definition"
    },
    "events": {
      "type": "array",
      "description": "Workflow event definitions. Defines events that can be consumed or produced",
      "items": {
        "type": "object",
        "$ref": "events/eventdef.json"
      }
    },
    "functions": {
      "type": "array",
      "description": "Workflow functions",
      "items": {
        "type": "object",
        "$ref": "functions/function.json"
      }
    },
    "states": {
      "type": "array",
      "description": "State Definitions",
      "items": {
        "type": "object",
        "existingJavaType": "io.cncf.serverlessworkflow.api.interfaces.State",
        "anyOf": [
          {
            "title": "Delay State",
            "$ref": "states/delaystate.json"
          },
          {
            "title": "Event State",
            "$ref": "states/eventstate.json"
          },
          {
            "title": "Operation State",
            "$ref": "states/operationstate.json"
          },
          {
            "title": "Parallel State",
            "$ref": "states/parallelstate.json"
          },
          {
            "title": "Switch State",
            "$ref": "states/switchstate.json"
          },
          {
            "title": "SubFlow State",
            "$ref": "states/subflowstate.json"
          },
          {
            "title": "Relay State",
            "$ref": "states/injectstate.json"
          },
          {
            "title": "ForEach State",
            "$ref": "states/foreachstate.json"
          },
          {
            "title": "Callback State",
            "$ref": "states/callbackstate.json"
          }
        ]
      }
    },
    "extensions": {
      "type": "array",
      "description": "Workflow Extensions",
      "items": {
        "type": "object",
        "existingJavaType": "io.cncf.serverlessworkflow.api.interfaces.Extension"
      }
    }
  },
  "required": [
    "id",
    "name",
    "version",
    "states"
  ]
}

=== serverlessworkflow/specification/sdk/java/api/src/test/resources/examples/solvemathproblems.json
{
  "id": "solvemathproblems",
  "version": "1.0",
  "name": "Solve Math Problems Workflow",
  "description": "Solve math problems",
  "functions": [
    {
      "name": "solveMathExpressionFunction",
      "resource": "functionResourse"
    }
  ],
  "states":[
    {
      "name":"Solve",
      "type":"foreach",
      "start": {
        "kind": "default"
      },
      "inputCollection": "$.expressions",
      "inputParameter": "$.singleexpression",
      "outputCollection": "$.results",
      "states": [
        {
          "name":"GetResults",
          "type":"operation",
          "start": {
            "kind": "default"
          },
          "actionMode":"sequential",
          "actions":[
            {
              "functionRef": {
                "refName": "solveMathExpressionFunction",
                "parameters": {
                  "expression": "$.singleexpression"
                }
              }
            }
          ],
          "end": {
            "kind": "default"
          }
        }
      ],
      "stateDataFilter": {
        "dataOutputPath": "$.results"
      },
      "end": {
        "kind": "default"
      }
    }
  ]
}

=== serverlessworkflow/specification/sdk/java/api/src/test/resources/examples/vetappointmentservice.json
{
  "id": "VetAppointmentWorkflow",
  "name": "Vet Appointment Service Workflow",
  "description": "Vet service call via events",
  "version": "1.0",
  "events": [
    {
      "name": "MakeVetAppointment",
      "source": "VetServiceSoure",
      "kind": "produced"
    },
    {
      "name": "VetAppointmentInfo",
      "source": "VetServiceSource",
      "kind": "consumed"
    }
  ],
  "states": [
    {
      "name": "MakeVetAppointmentState",
      "type": "operation",
      "start": {
        "kind": "default"
      },
      "actions": [
        {
          "name": "MakeAppointmentAction",
          "eventRef": {
            "triggerEventRef": "MakeVetAppointment",
            "data": "$.patientInfo",
            "resultEventRef":  "VetAppointmentInfo"
          },
          "actionDataFilter": {
            "dataResultsPath": "$.appointmentInfo"
          },
          "timeout": "PT15M"
        }
      ],
      "end": {
        "kind": "default"
      }
    }
  ]
}

=== serverlessworkflow/specification/sdk/java/api/src/test/resources/examples/foreachstatewithactions.json
{
  "id": "foreachstatewithactions",
  "name": "ForEach State With Actions",
  "description": "ForEach State With Actions",
  "version": "1.0",
  "functions": [
    {
      "name": "sendConfirmationFunction",
      "resource": "functionResourse"
    }
  ],
  "states": [
    {
      "name":"SendConfirmationForEachCompletedhOrder",
      "type":"foreach",
      "inputCollection": "$.orders[?(@.completed == true)]",
      "inputParameter": "$.completedorder",
      "actions":[
        {
          "functionRef": {
            "refName": "sendConfirmationFunction",
            "parameters": {
              "orderNumber": "$.completedorder.orderNumber",
              "email": "$.completedorder.email"
            }
          }
        }],
      "end": {
        "kind": "default"
      }
    }
  ]
}

=== serverlessworkflow/specification/sdk/java/api/src/test/resources/examples/finalizecollegeapplication.json
{
  "id": "finalizeCollegeApplication",
  "name": "Finalize College Application",
  "version": "1.0",
  "events": [
    {
      "name": "ApplicationSubmitted",
      "type": "org.application.submitted",
      "source": "applicationsource",
      "correlationToken": "applicantId"
    },
    {
      "name": "SATScoresReceived",
      "type": "org.application.satscores",
      "source": "applicationsource",
      "correlationToken": "applicantId"
    },
    {
      "name": "RecommendationLetterReceived",
      "type": "org.application.recommendationLetter",
      "source": "applicationsource",
      "correlationToken": "applicantId"
    }
  ],
  "functions": [
    {
      "name": "finalizeApplicationFunction",
      "type": "function",
      "resource": "finalizeApplicationResource"
    }
  ],
  "states": [
    {
      "name": "FinalizeApplication",
      "type": "event",
      "start": {
        "kind": "default"
      },
      "exclusive": false,
      "eventsActions": [
        {
          "eventRefs": [
            "ApplicationSubmitted",
            "SATScoresReceived",
            "RecommendationLetterReceived"
          ],
          "actions": [
            {
              "functionRef": {
                "refName": "finalizeApplicationFunction",
                "parameters": {
                  "student": "$.applicantId"
                }
              }
            }
          ]
        }
      ],
      "end": {
        "kind": "terminate"
      }
    }
  ]
}

=== serverlessworkflow/specification/sdk/java/api/src/test/resources/examples/greeting.json
{
  "id": "greeting",
  "version": "1.0",
  "name": "Greeting Workflow",
  "description": "Greet Someone",
  "functions": [
    {
      "name": "greetingFunction",
      "resource": "functionResourse"
    }
  ],
  "states":[
    {
      "name":"Greet",
      "type":"operation",
      "start": {
        "kind": "default"
      },
      "actionMode":"sequential",
      "actions":[
        {
          "functionRef": {
            "refName": "greetingFunction",
            "parameters": {
              "name": "$.greet.name"
            }
          },
          "actionDataFilter": {
            "dataResultsPath": "$.payload.greeting"
          }
        }
      ],
      "stateDataFilter": {
        "dataOutputPath": "$.greeting"
      },
      "end": {
        "kind": "default"
      }
    }
  ]
}

=== serverlessworkflow/specification/sdk/java/api/src/test/resources/examples/carauctionbids.json
{
  "id": "handleCarAuctionBid",
  "version": "1.0",
  "name": "Car Auction Bidding Workflow",
  "description": "Store a single bid whole the car auction is active",
  "functions": [
    {
      "name": "StoreBidFunction",
      "resource": "storeBidResource",
      "type": "function"
    }
  ],
  "events": [
    {
      "name": "CarBidEvent",
      "type": "carBidMadeType",
      "source": "carBidEventSource"
    }
  ],
  "states": [
    {
      "name": "StoreCarAuctionBid",
      "type": "event",
      "start": {
        "kind": "scheduled",
        "schedule": {
          "interval": "2020-03-20T09:00:00Z/2020-03-20T15:00:00Z"
        }
      },
      "exclusive": true,
      "eventsActions": [
        {
          "eventRefs": ["CarBidEvent"],
          "actions": [{
            "functionRef": {
              "refName": "StoreBidFunction",
              "parameters": {
                "bid": "$.bid"
              }
            }
          }]
        }
      ],
      "end": {
        "kind": "terminate"
      }
    }
  ]
}
